### ISSUE TITLE
Turbo stream envelope broken for SSE integration

### ISSUE THREAD

**Issue by jabrena** [odrotbohm/spring-playground#2]
Hi Oliver,

I am testing the snapshot and I have few questions:

```xml
<dependencies>
  <dependency>
    <groupId>de.odrotbohm.playground</groupId>
    <artifactId>hotwire-spring-boot</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  <dependency>
</dependencies>
```

- stream message
- websocket support

**stream message**
I am reviewing in Chrome Dev Tools the following structure:

```xml
<turbo-stream action="replace" target="load">
<template>
<span id="load">2.64208984375</span>
</turbo-stream>
</turbo-stream>
```

Is it possible that the messaage doesn´t close the template tag?

**websocket support**
why in the first snapshot, you didn´t add websocket support?

Many thanks in advance

Juan Antonio

**Comment by odrotbohm** [comment]
The broken closing tag is in fact a glitch. I'll fix that right away.

Regarding the Websocket stuff. I just didn't get to it yet and got busy with other stuff. Wouldn't mind to see a contribution though!

**Comment by odrotbohm** [comment]
I've created #3 to capture work on the Websocket integration so that we can fix the SSE stuff for this ticket.

**Comment by jabrena** [comment]
Hi @odrotbohm ,

“ Wouldn't mind to see a contribution though!” I could be a pleasure. I continue reviewing the current snapshot but yes, why not.

cheers

Juan Antonio
